[build]
  command = "npm run build"   # spustí náš 'fake' build, aby Netlify bežal build krok
  publish = "."               # koreň repozitára
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
  Cache-Control = "no-cache, no-store, must-revalidate"
